name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-docker-image-base:
    runs-on: ubuntu-20.04
    name: "Build Docker images"
    env:
      REPO: pufferpanel/pufferpanel
      VERSION: latest
    strategy:
      matrix:
        platform: ["linux/amd64"]

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build master container
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        build-args: |
          sha: ${{ github.sha }}
          version: ${{ env.VERSION }}
        platforms: ${{ matrix.platform }}
        
